### ISSUE TITLE
Custom search providers not appearing as commands

### ISSUE THREAD

**Issue by Nabav** [platinumjesus/vscode-advanced-search-extension#8]
After editing the default search providers in settings, I cannot use them. This is because the old fixed search engines are listed as commands in command pallette.

Running the fixed commands will result in error:

`Command 'Web Search: Google' resulted in an error (command 'websearch.google' not found)`

**Comment by platinumjesus** [comment]
I see, do you feel like doing a fix PR? 

If not I am taking care of this. Thanks for reporting!

**Comment by Nabav** [comment]
> I see, do you feel like doing a fix PR?
> 
> If not I am taking care of this. Thanks for reporting!

Sorry, unfortunately I cannot do this.

**Comment by bveldkamp** [comment]
I'm having the same issue, has this been fixed yet?

**Comment by platinumjesus** [comment]
Hello @bveldkamp I refactored a lot the code in master but I have not created a release, unfortunately it is not possible yet to have this feature as commands in vscode cannot be dynamically created by user configurations, but they must be hardcoded in the extension package. That is as much as I know, at least. 

Even new version cannot fix this, unfortunately.

**Comment by bveldkamp** [comment]
Oh, that's too bad. 

Something that would help me a lot is if I could open a configured URL based on the current file extension. That way, no extra commands would need to be added. My goal is to open a page with context sensitive help, e.g. if I have a C# file open, it would open a specific MSDN page, if I have a Python file open, it would go to python.org and so on.
